### ISSUE TITLE
Plated is not stack safe

### ISSUE THREAD

**Issue by julien-truffaut** [julien-truffaut/Monocle#323]
```scala
import io.circe.Json
import io.circe.optics.all._
import io.circe.parse.parse
import monocle.Iso
import monocle.function.Plated
import monocle.function.all._

object PlatedExample extends App {
  val json =
    """{
      |  "name" : "john",
      |  "age" : 24,
      |  "other" : {
      |    "name" : "robert",
      |    "age"  : 12
      |  }
      |}
    """.stripMargin

  val doc: Json = parse(json).getOrElse(Json.empty)

  universe(doc)
    .map(_.asObject.flatMap(_("name")))
    .collect{case Some(a) => a }
    .foreach(println)
  // "john"
  // "robert"

  println(
    Plated.rewriteOf(
      (Iso.id[Json] composePrism jsonObject composeOptional index("name")).asSetter
    )(_.as[String].toOption.map(_.capitalize).map(Json.string))(doc)
  )

}
```

produces the following error: 
```
Exception in thread "main" java.lang.StackOverflowError
	at monocle.Prism$$anon$7.getOrModify(Prism.scala:262)
	at monocle.PPrism$$anon$1$$anonfun$getOrModify$1.apply(Prism.scala:149)
	at monocle.PPrism$$anon$1$$anonfun$getOrModify$1.apply(Prism.scala:149)
	at scalaz.$bslash$div.flatMap(Either.scala:135)
	at monocle.PPrism$$anon$1.getOrModify(Prism.scala:149)
	at monocle.PPrism$$anonfun$modify$1.apply(Prism.scala:53)
	at monocle.function.PlatedFunctions$class.transformOf(Plated.scala:63)
	at monocle.function.Plated$.transformOf(Plated.scala:20)
	at monocle.function.PlatedFunctions$class.go$2(Plated.scala:51)
	at monocle.function.PlatedFunctions$$anonfun$go$2$2.apply(Plated.scala:52)
	at scala.Option.fold(Option.scala:158)
	at monocle.function.PlatedFunctions$class.go$2(Plated.scala:52)
	at monocle.function.PlatedFunctions$$anonfun$go$2$2.apply(Plated.scala:52)
	at scala.Option.fold(Option.scala:158)
	at monocle.function.PlatedFunctions$class.go$2(Plated.scala:52)
	at monocle.function.PlatedFunctions$$anonfun$go$2$2.apply(Plated.scala:52)
```

**Comment by julien-truffaut** [comment]
It seems to come from the fact I tried to modify a child of `JsonObject` see `rewriteOf` javadoc: 
```
rewrite a target by applying a rule within a [[Setter]], as often as
possible until it reaches a fixpoint (this is an infinite loop if there is
no fixpoint)
```
