### ISSUE TITLE
NoSuchElementException

### ISSUE THREAD

**Issue by newhoggy** [julien-truffaut/Monocle#374]
```
java.util.NoSuchElementException: key not found: Map(...)
  at scala.collection.MapLike$class.default(MapLike.scala:228)
  at scala.collection.AbstractMap.default(Map.scala:59)
  at scala.collection.MapLike$class.apply(MapLike.scala:141)
  at scala.collection.AbstractMap.apply(Map.scala:59)
  at monocle.Prism$$anon$7.reverseGet(Prism.scala:292)
  at monocle.PPrism$$anonfun$modify$1$$anonfun$apply$4.apply(Prism.scala:55)
  at scalaz.$bslash$div.fold(Either.scala:58)
  at monocle.PPrism$$anonfun$modify$1.apply(Prism.scala:55)
  at monocle.PPrism$$anonfun$modify$1$$anonfun$apply$4.apply(Prism.scala:55)
  at scalaz.$bslash$div.fold(Either.scala:58)
  at monocle.PPrism$$anonfun$modify$1.apply(Prism.scala:55)
  at monocle.PLens$$anon$7$$anonfun$modify$1.apply(Lens.scala:239)
  at monocle.PPrism$$anonfun$modify$1$$anonfun$apply$4.apply(Prism.scala:55)
  at scalaz.$bslash$div.fold(Either.scala:58)
  at monocle.PPrism$$anonfun$modify$1.apply(Prism.scala:55)
  at monocle.PPrism$$anonfun$modify$1$$anonfun$apply$4.apply(Prism.scala:55)
  at scalaz.$bslash$div.fold(Either.scala:58)
  at monocle.PPrism$$anonfun$modify$1.apply(Prism.scala:55)
  at monocle.PLens$$anon$7$$anonfun$modify$1.apply(Lens.scala:239)
  at monocle.PPrism$$anonfun$modify$1$$anonfun$apply$4.apply(Prism.scala:55)
  at scalaz.$bslash$div.fold(Either.scala:58)
  at monocle.PPrism$$anonfun$modify$1.apply(Prism.scala:55)
  at scala.Function1$$anonfun$andThen$1.apply(Function1.scala:52)
  at scala.Function1$$anonfun$andThen$1.apply(Function1.scala:52)
  at scala.Function1$$anonfun$andThen$1.apply(Function1.scala:52)
  at scala.Function1$$anonfun$andThen$1.apply(Function1.scala:52)
```

My code is:

```
import argonaut.Argonaut._
import argonaut.JsonMonocle._
import argonaut._
import monocle._
import monocle.function.Each.each
import monocle.function.{At, Index}
import monocle.std.list._
import monocle.std.map._

val jObjectFieldsPrism =
  Prism[Json, Map[JsonField, Json]](
    _.fold(None,
      _ => None,
      _ => None,
      _ => None,
      _ => None,
      o => Some(o.toMap))
  )(Map.empty)

val triggersLens =
  jObjectFieldsPrism ^|-? index("attack")     ^<-?
  jObjectFieldsPrism ^|-? index("triggers")   ^<-?
  jObjectFieldsPrism ^|-? index("item")
```

I am using `argonaut-monocle 6.2-M3` and `monocle 1.2.2`

**Comment by julien-truffaut** [comment]
answered in argonaut
